hydra:
  searchpath:
    - file://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

data:
  gen_batch_size: ${data.train_batch_size}

reward_model:
  reward_manager: dapo
  overlong_buffer: 
    enable: False
    len: 0
    penalty_factor: 0.0
    log: False

algorithm:
  # adv_estimator can be 'remax' or 'gae' (for gspo-ib)
  adv_estimator: gae
  filter_groups:
    _target_: verl.trainer.config.FilterGroupsConfig
    enable: False # We try to avoid forgetting to set enable
    metric: null # acc / score / seq_reward / seq_final_reward / ...
    max_num_gen_batches: 0 # Non-positive values mean no upper limit
  
  # GSPO-IB specific params
  eta: 1.0
  gamma: 1.0

trainer:
  project_name: verl-gspo-ib-dapo
